### ISSUE TITLE
How to send/recieve data through the network

### ISSUE THREAD

**Issue by ahmedelhaddad** [binnes/WiFiMeshRaspberryPi#10]
I have two drones, 1 gateway and the other is bridge, i have a pozyx device attached to the rpi where it returns to me the xyz coordinates in a 3d plane. How do i send commands or recieve info from the drones on my laptop whether its data or photos.

I am currently implementing the wifi bridge part so its not over yet however I want to know what to expect

**Comment by tim292stro** [comment]
My recommendation is for you to set up the kind of communication you want to try on a hardwired network first - the mesh is "just a network".  If you are at a point where the mesh nodes can see each other, you have essentially reached parity with a hardwired network connection as far as transport availability is concerned (this does not include bandwidth, throughput, etc.).
  
You may be running into other issues or missing components to transfer data between nodes in a useful way - and I find that doing the development on a hardwired connection between two nodes removes the doubt that "it might be the mesh that's doing it".  YMMV

**Comment by ahmedelhaddad** [comment]
> My recommendation is for you to set up the kind of communication you want to try on a hardwired network first - the mesh is "just a network". If you are at a point where the mesh nodes can see each other, you have essentially reached parity with a hardwired network connection as far as transport availability is concerned (this does not include bandwidth, throughput, etc.).
> 
> You may be running into other issues or missing components to transfer data between nodes in a useful way - and I find that doing the development on a hardwired connection between two nodes removes the doubt that "it might be the mesh that's doing it". YMMV

im really sorry but im having a hard time understanding what you're saying. Can you clarify a bit, im a total newbie and this is my first time dealing with rpi and networks in general

**Comment by tim292stro** [comment]
Simply, if you can't get it to work with two RaspberryPi's connected to each other with a Cat5, adding in a mesh is not going to make your learning experience any easier.
  
As you say this is your first time dealing with networks - there is a lot to learn on simple networking principals.
  
You have a "thing" that generates data.  You have a place where you want to use the data that is not where the data is generated.  That basically describes the client server architecture.
  
Your data generation is the server, the place that you use the data is the client.  Just because you can use the data locally on the "server" doesn't mean it's exposing the data for external users to access.  This may require an additional component like a webserver or MQTT etc...
  
Between the server and the network there may be other things like firewalls etc. which prevent external devices from accessing the data you are generating.  Then on the client you may need something additional to ingest the data and present it the local client in a way the client can use.
