### ISSUE TITLE
Issue with Bridge Node

### ISSUE THREAD

**Issue by normandmickey** [binnes/WiFiMeshRaspberryPi#2]
I successfully created the gateway and second nodes.  However after turning the second node into a Bridge it doesn't get a  192.168.199.x address and is unable to ping the gateway (192.168.199.1).  Anything connected to eth0 on the Bridge cannot reach the internet either.  

Any suggestions?

**Comment by normandmickey** [comment]
I managed to get the bridge node to work by adding 'sudo ifconfig br0 up' at the bottom of the start-batman-adv.sh script.  This appears to allow devices connected to the bridge to reach mesh neighbors and the internet.  However the bridge node itself cannot do either. 

# Activates batman-adv interfaces
sudo ifconfig wlan0 up
sudo ifconfig bat0 up
sudo ifconfig br0 up

**Comment by binnes** [comment]
Can you confirm that:
- you are in Part 1 - just using Ethernet (no second WiFi ports)
- you have checked all the files, and the content matches 
  - ~/start-batman-adv.sh
  - /etc/network/interfaces.d/wlan0
  - /etc/dhcpcd.conf
  - /etc/rc.local
  - /etc/network/interfaces.d/eth0
  - /etc/dhcpcd.conf
 Can you also confirm that when verifying the bridge node you see the correct output with **ifconfig**, **brctl show**, **batctl if** and **batctl n** commands

Without the output of the above commands it is difficult to advise where the issue lies, but going through the steps in the instructions to verify the bridge node should identify where the issue is.

**Comment by normandmickey** [comment]
Thanks for the reply.  I spent a lot of time double checking all of the
settings this weekend and couldn't get the eth0 bridge to work.  I will go
back through the process and see if I can provide more detail.

This morning I decided to move on and add a second wireless adapter to the
bridge and both interfaces appear to work now.  However I get the following
error when booting "device br0 already exists; can't create bridge with the
same name".

Norm

**Comment by nitin-rakheja** [comment]
Hi Binnes,

Have you been able to resolve this issue? I am facing the exactly similar problem. 

I have setup the mesh on Raspberry Pi 4 Model B. Using two such boards and my Macbook, I have setup one Gateway and one Bridge. However, the bridge doesnt acquire the 192.168.199.x address from the dnsmasq of the Gateway.

The br0 doesnt show up on the ifconfig unless I force it to start by initiating the command ifconfig br0 up

The Bridge is unable to ping the Gateway and continues to retain the IP of 169.254.89.206

My macbook cant connect to the Bridge since the IP from the Gateway doesnt flow down to it.

Thanks,
Nitin

**Comment by binnes** [comment]
Hello Nitin,

As I said in my previous post without any diagnostic data it is very difficult to speculate what is going on and why your environment isn't working.  There are a lot of factors that need to fall into place to get this working end to end.  It may be that the instructions need updating, but a number of testers have gone through this and got it to work successfully, both the original post and the update for Raspberry Pi 4 and updated Raspbian.

It would also help to clarify exactly what step you are at - are you working on Ethernet connectivity or did you skip to WiFi?

**Comment by nitin-rakheja** [comment]
Hi Brian,

I am using Raspberry Pi 4 Model B boards to setup a mesh network. Currently I have two of these boards. Both have been installed with Buster Version 10. These boards have ‘onboard WiFi’. I have setup the boards as per https://github.com/binnes/WiFiMeshRaspberryPi

Step 1
I first configured both the boards with batman-adv exactly as per Part 1 – Mesh Networks. Thus both boards were forming a mesh.

Step 2
Thereafter I configured one of these boards as a Gateway (exactly the way its mentioned in Part 1 – Network Access). Herein, the Mesh is using bat0 which is running on wlan (wlan0) and the Gateway is accessing the internet on eth0. 

The Gateway is functioning fine. Further, along with the Gateway, the second Pi is working well as a Mesh node and is able to ping the Gateway as well as reach the internet. 

Step 3
Then I configured the second Pi as a Bridge (again following the commands from Part 1 – Network Access). In this case the br0 is using interfaces bat0 and eth0. This is where I am facing a problem. The configuration of the Bridge is as below :-

**/etc/network/interfaces.d/wlan0**
auto wlan0
iface wlan0 inet manual
wireless-channel 1
wireless-essid call-code-mesh
wireless-mode ad-hoc

**/etc/network/interfaces.d/eth0**
auto eth0
allow-hotplug eth0
iface eth0 inet manual

**~/start-batman-adv.sh**

```
#!/bin/bash
# batman-adv interface to use
sudo batctl if add wlan0
sudo ifconfig bat0 mtu 1468

sudo brctl addbr br0
sudo brctl addif br0 eth0 bat0

# Tell batman-adv this is a gateway client
sudo batctl gw_mode client

# Activates batman-adv interfaces
sudo ifconfig wlan0 up
sudo ifconfig bat0 up
```

**/etc/dhcpcd.conf**
denyinterfaces wlan0 eth0 bat0

**/etc/modules**
i2c-dev
batman-adv

**/etc/rc.local**
/home/pi/start-batman-adv.sh & (before last line exit 0)

Output of verification commands

**$ brctl show**
bridge name	bridge ID	STP Enabled	Interfaces
br0	8000.6e5….1	no	                          bat0
			                                          eth0
**$ batctl if**
wlan0 : active

**$ sudo batctl n**
shows the other pi as neighbor

**$sudo batctl o**
shows the other pi as next hop

**$  ifconfig**
shows 
bat0 – without IP address
eth0 – without IP address
l0  - inet 127.0.0.1 netmask 255.0.0.0
wlan0 – without IP address

**$ iwconfig**
lo	no wireless extension 
wlan0	IEE 802.11	ESSID : “ call-code-mesh “
	         Mode : Ad-Hoc	Frequency ……..
br0	no wireless extension
eth0	no wireless extension
bat0	no wireless extension


The problem I am facing is:-
1.  Once configured as a Bridge, the br0 is not seen in the output of command ifconfig
2.  When I type command sudo ifconfig br0 up, the br0 comes up in the output of command ifconfig but without an IP address
3.  If I connect my Laptop to this bridge pi on eth0, my laptop acquires the IP from the Gateway and is able to ping internet, however the bridge pi hosting itself neither acquires an IP address nor is able to ping the internet
4.  Theoretically, since the bridge pi is unable to ping the gateway, it shall be unable to ping any other mesh node and viceversa 
5.  As long as the bridge node was configured only as a mesh node, it was connecting to bat0 in the network. However, now after I configure it as a bridge, the network shows “not connected”.

Thanks,
Nitin

**Comment by binnes** [comment]
Hi Nitin,  
Thanks for the information.  Quite puzzled that in point 3 - connecting your laptop to the Ethernet port on the bridge enables the laptop to get an IP address from the gateway node and you are able to connect to the internet.  This suggests that the bridge is up and running and there is IP connectivity across the mesh, but the output of the tests shows the bridge interface isn't configured correctly and doesn't have an IP address?

Let me go do some investigation, see if I can work out what is going on.

**Comment by nitin-rakheja** [comment]
Hi Brian,

If I make the following changes:-
1.  Change the /etc/dhcpcd.conf wherein instead of denyinterfaces wlan0 eth0 bat0, I remove bat0 and let the command only denyinterfaces wlan0 eth0

2.  Add an interface br0 in the /etc/network/interfaces.d/br0 with the following configuration
auto br0
iface br0 inet manual

3.  Add to the ~/start-batman-adv.sh 
sudo ifconfig br0 up

the result is,
1.  The bat0 interface on the bridge gets configured with an IP address from the gateway
2.  The br0 interface shows up in the ifconfig output
3.  A laptop connected to the bridge on the eth0 acquires an IP from the Gateway and is able to connect to the internet

the unresolved issues are
1.  In the ifconfig output, br0 comes up without an IP address. 
2.  In the ifconfig output, bat0 comes up with an IP address acquired from the Gateway
3.  The bridge node, although showing bat0 interface configured with an IP address of the same subnet as the Gateway, is unable to ping the Gateway or connect to the internet 
4.  The Laptop connected to the bridge on the eth0 is able to ping the Gateway and connect to the internet however, it is unable to ping the bridge on the bat0 IP address of the bridge 

(Just to mention
 From the changes I have listed above, the second change of addition of an interface br0 in the /etc/network/interfaces.d/br0 , even if not created makes no difference to the rest of the result. )

**Comment by binnes** [comment]
The bat interface needs to be part of the bridge, or traffic won't get forwarded from your laptop. I think the issue is there is a race condition going on.  It looks like the bridge is being created OK, but the DHCPclient isn't working on the interface.  As a test add the following to the end of the start-batman-adv.sh file **sudo dhclient br0**, so the file now looks like:

```bash
#!/bin/bash
# batman-adv interface to use
sudo batctl if add wlan0
sudo ifconfig bat0 mtu 1468

sudo brctl addbr br0
sudo brctl addif br0 eth0 bat0

# Tell batman-adv this is a gateway client
sudo batctl gw_mode client

# Activates batman-adv interfaces
sudo ifconfig wlan0 up
sudo ifconfig bat0 up

sudo dhclient br0
```

With all the rest of the files as specified in the instructions.  Does this work for you?

**Comment by nitin-rakheja** [comment]
BINGO !!

It works like a charm !!

**Thanks Brian.**

 I now have a Mesh of two raspberry pi 4 model B with one of them acting as a Gateway and the other as a Bridge in addition to being part of the Mesh. And the network works flawlessly.

Thanks again.

**Comment by tntniiga** [comment]
Hi binnes,
I've seen your work and completed part 1 with no problems. But moving to part 2, i dont really understand what you meant by saying "replace wlan0 with wlan1 in all the previous configuration completed in part 1 and switch wlan0 and wlan1 in the following configuration." 
For example: 
sudo nano /etc/network/interfaces.d/wlan0 
Do i have to create another file "wlan1" and set the content with wlan1 or i just need to replace wlan0 with wlan1 in "wlan0" file?
And do i have to replace wlan0 with wlan1 for just the gateway rapberrypi or all of the raspberrypis ?

**Comment by gsleo1976** [comment]
Hello Brian, 

Sometimes back I followed your instructions and successfully created the mesh network.
But I tried today again and it shows me error "wlan0: error reading status".

I have closely tried all the instructions twice with a fresh image from Raspberry site.
I am configuring one Pi for Gateway and another for Bridge.
Followed the instructions very closely in Part1.
But it shows same error like this

pi@rpi-brg-4gb:~ $ sudo batctl if
wlan0: error reading status



****Details****

****my gateway looks like this**** 

**pi@rpi-gtw-1gb:~ $ ifconfig**
bat0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1468
        inet 192.168.199.1  netmask 255.255.255.0  broadcast 192.168.199.255
        inet6 fe80::36c5:e5f6:4e13:9df8  prefixlen 64  scopeid 0x20<link>
        ether 1e:1a:0c:49:4c:81  txqueuelen 1000  (Ethernet)
        RX packets 21  bytes 1460 (1.4 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3  bytes 304 (304.0 B)
        TX errors 0  dropped 45 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.34  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::d6aa:4ac5:b976:548a  prefixlen 64  scopeid 0x20<link>
        ether b8:27:eb:9f:ee:3b  txqueuelen 1000  (Ethernet)
        RX packets 1187  bytes 59140 (57.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 117  bytes 14893 (14.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 95  bytes 7546 (7.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 95  bytes 7546 (7.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::7edd:90ff:fe47:4507  prefixlen 64  scopeid 0x20<link>
        ether 7c:dd:90:47:45:07  txqueuelen 1000  (Ethernet)
        RX packets 117  bytes 9729 (9.5 KiB)
        RX errors 0  dropped 4  overruns 0  frame 0
        TX packets 133  bytes 13669 (13.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


**pi@rpi-gtw-1gb:~ $ iwconfig**
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     IEEE 802.11  ESSID:"call-code-mesh"  
          Mode:Ad-Hoc  Frequency:2.412 GHz  Cell: EE:99:7A:6C:F5:07   
          Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:on
          
bat0      no wireless extensions.


**pi@rpi-gtw-1gb:~ $ sudo batctl if**
wlan0: <error reading status>


**pi@rpi-gtw-1gb:~ $ sudo batctl n**
Error - interface bat0 is not present or not a batman-adv interface


****my bridge looks like this****

**pi@rpi-brg-4gb:~ $ ifconfig**
bat0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1468
        inet6 fe80::8a6:7ff:feb8:a14a  prefixlen 64  scopeid 0x20<link>
        ether 0a:a6:07:b8:a1:4a  txqueuelen 1000  (Ethernet)
        RX packets 33  bytes 1386 (1.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 3557  bytes 213767 (208.7 KiB)
        TX errors 0  dropped 225 overruns 0  carrier 0  collisions 0

br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1468
        inet 192.168.1.4  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::8a6:7ff:feb8:a14a  prefixlen 64  scopeid 0x20<link>
        ether 0a:a6:07:b8:a1:4a  txqueuelen 1000  (Ethernet)
        RX packets 3995  bytes 197842 (193.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 286  bytes 31309 (30.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::dea6:32ff:feb7:dd6b  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:b7:dd:6b  txqueuelen 1000  (Ethernet)
        RX packets 4031  bytes 257826 (251.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 331  bytes 33904 (33.1 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8  bytes 480 (480.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 480 (480.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::dea6:32ff:feb7:dd6c  prefixlen 64  scopeid 0x20<link>
        ether dc:a6:32:b7:dd:6c  txqueuelen 1000  (Ethernet)
        RX packets 94  bytes 6715 (6.5 KiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 359  bytes 37300 (36.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0



**pi@rpi-brg-4gb:~ $ sudo brctl show**
bridge name	bridge id		STP enabled	interfaces
br0		8000.0aa607b8a14a	no		bat0
							eth0

**pi@rpi-brg-4gb:~ $ sudo batctl if**
wlan0: error reading status


**pi@rpi-brg-4gb:~ $ sudo batctl n**
Error - interface bat0 is not present or not a batman-adv interface.


Please suggest me what could be the possible reason for this.
your guide is excellent material on mesh networking. 
Thanks for educating the community on mesh networking. 

Regards
Leo

**Comment by binnes** [comment]
Hi Leo,  Can you provide details of hardware (version of Pi hardware, on-board/external WiFi, version of RaspberryPi OS being used, etc...) so I can test the instructions using a similar setup?

**Comment by gsleo1976** [comment]
Hi Brian, 

Here are the details:

**Gateway**
Raspberry Pi 2 Model B Rev 1.1
5.10.11-v7+ #1399 SMP Thu Jan 28 12:06:05 GMT 2021 armv7l GNU/Linux
USB WiFi (Realtek Semiconductor Corp. RTL8188CUS 802.11n WLAN Adapter)


**Bridge**
Raspberry Pi 4 Model B Rev 1.2
5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
On-board WiFi

Thanks
Leo

**Comment by gsleo1976** [comment]
Hello Brian, 

Any clue please...

Thanks

**Comment by koeller21** [comment]
Hi Leo,

I had the same issue with batctl not being able to display the interface state properly. 
What temporarily resolved this for me, was to use an older RaspianOS version.
I used 4.19.75 (http://downloads.raspberrypi.org/raspbian/images/raspbian-2019-09-30/) and it resolved that issue for me.

**Comment by tim292stro** [comment]
Note that this issue is closed.

The RaspberryPi Raspbian libraries - tend to be out of date as described in the open issue: [https://github.com/binnes/WiFiMeshRaspberryPi/issues/6](https://github.com/binnes/WiFiMeshRaspberryPi/issues/6).  The new kernel used in the latest Raspbian Linux images has a new kernel but it was compiled with the old batman-adv-yyyy.v kernel driver.

Running the latest Raspbian and compiling from the command line as described in the above linked-issue worked perfectly.  This is a Raspbian release bug (they should have pulled the latest libraries at compile-time).

**Comment by gsleo1976** [comment]
Thanks Koeller22 for the update.
I will definitely try it.

**Comment by Zeddy-** [comment]
Thanks for this, also had the same error with the latest Kernel. Mesh network worked fine, but batctl if returned:
pi@ad-hoc-1:~ $ sudo batctl if
wlan0: <error reading status>
