### ISSUE TITLE
problem with part2

### ISSUE THREAD

**Issue by tntniiga** [binnes/WiFiMeshRaspberryPi#3]
Hi binnes,
I've seen your work and completed part 1 with no problems. But moving to part 2, i dont really understand what you meant by saying "replace wlan0 with wlan1 in all the previous configuration completed in part 1 and switch wlan0 and wlan1 in the following configuration."
For example:
sudo nano /etc/network/interfaces.d/wlan0
Do i have to create another file "wlan1" and set the content with wlan1 or i just need to replace wlan0 with wlan1 in "wlan0" file?
And do i have to replace wlan0 with wlan1 for just the gateway rapberrypi or all of the raspberrypis ?
Thank you!

**Comment by binnes** [comment]
Part 2 is the use case where you don't want the mesh connected to the home/office or Ad-hoc networks using Ethernet cables.  It converts the setup from part 1 to use WiFi connectivity.  If you are happy to use the Ethernet setup then you can skip to part 3.

If you want a total WiFi setup without Ethernet cables, then you need to create the additional WiFi interfaces on the Gateway and Bridge nodes Raspberry Pis, which is what part 2 will walk you through.  To do this you need to use USB WiFi dongles.

The comment about switching wlan0 with wlan1 is due to the automatic configuration when you attach a second WiFi interface by plugging in a USB dongle.  

The USB dongle is usually assigned to the **wlan0** interface by default if it is connected when the Raspberry Pi boots, so the built in wifi will now be **wlan1**.  If you want to keep the internal WiFi interface for the mesh then you need to modify the configuration you created in part 1 and replace the wifi interface **wlan0** with **wlan1** in all the configuration files.  

The reason you might want to choose which interface you want for the mesh and which to connect to the external networks is if the USB dongle and built in WiFi interfaces have different capabilities.  E.g. You may a WiFi dongle that supports both the 2.4GHz and 5GHz WiFi frequencies, but the internal WiFi only supports the 2.4GHz frequencies.

However, the instructions, as written uses **wlan0** as the mesh network interface and **wlan1** to connect to the external networks, so if you want the network interfaces to switch, then you will need to modify the configuration in the instructions.

This comment only applies to the Raspberry Pis you are adding a second WiFi network to (the bridge and gateway raspberry Pis)

Hope this helps?

**Comment by tntniiga** [comment]
Oh i see, you really just helped me understand part 2 deeper. Everything gets in its way now. 
Thank you very much for the explaination !
Keep up the good work !
